cmd_/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/addrconf_core-openvswitch.o := /Volumes/androidnew/kernel/msm/scripts/gcc-wrapper.py arm-linux-androideabi-gcc -Wp,-MD,/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/.addrconf_core-openvswitch.o.d  -nostdinc -isystem /Volumes/androidnew/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.6/bin/../lib/gcc/arm-linux-androideabi/4.6.x-google/include -I/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/include -I/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/compat -I/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/compat/include -I/Volumes/androidnew/kernel/msm/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include /Volumes/androidnew/kernel/msm/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-msm/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -marm -fno-dwarf2-cfi-asm -fstack-protector -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fomit-frame-pointer -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DVERSION=\"1.9.0\" -I/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/.. -I/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/.. -g -include /Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/kcompat.h  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(addrconf_core_openvswitch)"  -D"KBUILD_MODNAME=KBUILD_STR(openvswitch)" -c -o /Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/.tmp_addrconf_core-openvswitch.o /Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/addrconf_core-openvswitch.c

source_/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/addrconf_core-openvswitch.o := /Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/addrconf_core-openvswitch.c

deps_/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/addrconf_core-openvswitch.o := \
  /Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/kcompat.h \
  include/linux/version.h \

/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/addrconf_core-openvswitch.o: $(deps_/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/addrconf_core-openvswitch.o)

$(deps_/Users/umamaahmed/Documents/HotNet2013/openvswitch-1.9.0/datapath/linux/addrconf_core-openvswitch.o):
